### ISSUE TITLE
Blog posts not working

### ISSUE THREAD

**Issue by jocelynpender** [peterdesmet/petridish#46]
I'm not sure if this is an issue with Jekyll or with the petridish theme, so bear with me...

Blog posts show up on the homepage with no photo, tags, title, etc.: https://atlantichabitatmodels.github.io/communityofpractice/
Demo blog post: https://atlantichabitatmodels.github.io/communityofpractice/blog/2022-02-07-peibirds/
Demo blog post md file: https://github.com/atlantichabitatmodels/communityofpractice/blob/gh-pages/_posts/2022-02-07-peiBirds.md

This _was_ working in previous commits, so I'm fairly confident that the path to the image isn't the problem. I'm not sure what I did.

My [_config.yml ](https://github.com/atlantichabitatmodels/communityofpractice/blob/gh-pages/_config.yml) file looks VERY similar to the demo `_config.yml`. I tried playing around with the `_config.yml` settings, to no avail. I might just not be understanding how Jekyll works.

The only thing that I can think of to fix this is to delete the repo and create a new one with the same files, seeing as I'm not sure how to roll back commits with GitHub Pages... any advice is appreciated!

**Comment by peterdesmet** [comment]
@jocelynpender the reason the blog post does not work is because the title contains a colon `:`, breaking yaml frontmatter interpretation (of the title and any following things like background image and tags). This can be fixed by wrapping the whole title in quotes, so it is interpreted as one string.

In addition, the background image link should start with a `slash`. I have fixed this and some other issues in https://github.com/atlantichabitatmodels/communityofpractice/pull/3. If you accept that pull request, the blog post should work.

**Comment by jocelynpender** [comment]
Hey, thanks so much for your help!!! I accepted your helpful pull request and everything looks as it should wooooo! 😄💯
