### ISSUE TITLE
Internationalized examples?

### ISSUE THREAD

**Issue by dshorthouse** [peterdesmet/petridish#79]
Any examples or suggestions for how one might make use of this theme for a site that aspires to serve content (= navigation and pages) in multiple languages? Preferably, the URL paths should also be internationalized, though not a show-stopper.

**Comment by peterdesmet** [comment]
There is no elegant support or plugin out of the box, mainly because GitHub Pages restricts what Jekyll plugins can be used. But, luck would have it that I set up a multiple language site last month at https://github.com/inbo/vespa-watch/tree/gh-pages

What I did:

1. Organize (Markdown) pages in [language directories](https://github.com/inbo/vespa-watch/tree/gh-pages/pages) (`fr` content is only kept for archival reasons)
2. Create a navigation and footer [for each language](https://github.com/inbo/vespa-watch/tree/gh-pages/_data)
3. Set [frontmatter defaults](https://github.com/inbo/vespa-watch/blob/f4ca9919085a7536c0cd2a0dc78c85bd8b316741/_config.yml#L36-L52) to:
    -  serve content at correct URL i.e. `nl` content is served from root https://vespawatch.be/, `en` content from https://vespawatch.be/en/
    - set a `page.lang` variable
4. Create [custom `navbar.html` include](https://github.com/inbo/vespa-watch/blob/gh-pages/_includes/navbar.html) which will overwrite Petridish one. It:
    - Sets a number of [variables at the top](https://github.com/inbo/vespa-watch/blob/f4ca9919085a7536c0cd2a0dc78c85bd8b316741/_includes/navbar.html#L1-L9)
    - Includes a [language selector](https://github.com/inbo/vespa-watch/blob/f4ca9919085a7536c0cd2a0dc78c85bd8b316741/_includes/navbar.html#L71-L74). Note that this is a simplified version: since there are only 2 languages, it offers to _switch_ the language.
5. Create [custom `footer.html` include](https://github.com/inbo/vespa-watch/blob/gh-pages/_includes/footer.html)  which will overwrite Petridish one. The only change is that it includes [code](https://github.com/inbo/vespa-watch/blob/f4ca9919085a7536c0cd2a0dc78c85bd8b316741/_includes/footer.html#L65-L67) to select the correct footer.yml, rather than the default `_data/footer.yml` one.

You can see the result at https://vespawatch.be/

**Comment by peterdesmet** [comment]
Note: URL paths can be internationalized with this approach, since the [permalink picks up the name](https://github.com/inbo/vespa-watch/blob/gh-pages/_config.yml#L47) of the Markdown file:

```
permalink: /en/:basename/
```

I opted to name give the Markdown files the same names in Dutch and English (`pages/nl/get-involved.md` and `pages/en/get-involved.md`), so it's easier to understand what are the corresponding pages for each language. You can opt to give them different names or to set a custom `permalink` in the frontmatter for each page like this:

https://github.com/peterdesmet/petridish/blob/8f20d8b28498df630edc085c1a1251bafc4da7da/pages/docs/configuration.md?plain=1#L8

**Comment by dshorthouse** [comment]
Me & colleagues had been playing the "minimal mistakes" theme, but had been sucked into a blackhole. Restrictions on plugins is a v. useful piece of advice. And, thanks very much for this recipe. You may soon have another example that uses your gem :)~

**Comment by peterdesmet** [comment]
The limited or overly complicated customization of most existing Jekyll themes is why I started Petridish.

If you were _literally_ referring to a (Ruby) gem, note that I haven't implemented gem-based installation (#25 ). See http://peterdesmet.com/petridish/docs/installation/ for recommended installation.

If you were _figuratively_ referring to gem, carry on. 😄

**Comment by dshorthouse** [comment]
> If you were _literally_ referring to a (Ruby) gem, note that I haven't implemented gem-based installation (#25 ). See http://peterdesmet.com/petridish/docs/installation/ for recommended installation.

Ah! In that case, "You may soon have another example that uses your _nutrient agar_."
